development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: spoilers_dev
  pool: 5
  username: <%= Rails.application.credentials.mysql[:username] %>
  password: <%= Rails.application.credentials.mysql[:password] %>
  socket: /tmp/mysql.sock
  # socket: /opt/local/var/run/mysql5/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: spoilers_test
  pool: 5
  username: <%= Rails.application.credentials.mysql[:username] %>
  password: <%= Rails.application.credentials.mysql[:password] %>
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: spoilers_prod
  pool: 5
  username: <%= Rails.application.credentials.mysql[:username] %>
  password: <%= Rails.application.credentials.mysql[:password] %>
  socket: /tmp/mysql.sock
